[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Ignora warnings do FastAPI sobre on_event deprecated
filterwarnings =
    ignore::DeprecationWarning